[package]
name = "i_am_still_here"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
inputbot = "0.6.0"
tokio = { version = "1.37.0", features = ["full"]}
winapi = "0.3.9"